"""empty message

Revision ID: 47b7466ed6eb
Revises: 175b74b30acc
Create Date: 2023-01-30 20:32:36.686645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47b7466ed6eb'
down_revision = '175b74b30acc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customerFieldOfficer',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('firstname', sa.String(length=80), nullable=True),
    sa.Column('lastname', sa.String(length=80), nullable=True),
    sa.Column('phone', sa.String(length=15), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('poc',
    sa.Column('poc_code', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.Column('customer_email', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['customer_email'], ['customer.email'], ),
    sa.PrimaryKeyConstraint('poc_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poc')
    op.drop_table('customerFieldOfficer')
    # ### end Alembic commands ###
