"""empty message

Revision ID: f8905066afec
Revises: 47b7466ed6eb
Create Date: 2023-01-31 05:22:11.262317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8905066afec'
down_revision = '47b7466ed6eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disconnected_pay',
    sa.Column('_id', sa.Integer(), nullable=False),
    sa.Column('doc_name', sa.String(length=80), nullable=True),
    sa.Column('paymentdate', sa.DateTime(), nullable=True),
    sa.Column('poc_code', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['poc_code'], ['poc.poc_code'], ),
    sa.PrimaryKeyConstraint('_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('disconnected_pay')
    # ### end Alembic commands ###
